### ISSUE TITLE
Logic error: checking "contains" instead of "is" when matching exceptions

### ISSUE THREAD

**Issue by fiwswe** [cosmocode/dokuwiki-plugin-anonprotect#1]
While reading the code I noticed this logic error:

https://github.com/cosmocode/dokuwiki-plugin-anonprotect/blob/b82a6ab05a82db13b1e5e8430ad96cd773d6656a/action.php#L41

This will match any namespace exception whose name _contains_ the current namespace. What you probably want is is an exact test.

E.g.: list of exceptions: `widgets2024`, current namespace `widgets` will match and not block access to anonymous users. Thus access to namespace `widgets` is potentially allowed even though it is not listed in the `norestrictions` config setting.

Additionally it may be a good idea to convert `norestrictions` to lower case? I don't think capital letters are possible in namespaces.

Something like this might be what you want:
```php
                return $ns && $ns === strtolower(trim($skip));
```

**Comment by annda** [comment]
Thanks for the report and for spotting a potential weakness. I will add a test to make sure the matching is handled correctly.

But actually I do want to match on 'contains' rather than on 'is' because I want subspaces to match as well. So if `widgets2024` is the exception, I want `widgets2024:typeA` to match too.

Also, the logic does not check if the exception contains the current namespace, but whether the current namespace contains the exception, so your example will match as expected.

**Comment by fiwswe** [comment]
>So if `widgets2024` is the exception, I want `widgets2024:typeA` to match too.

Makes sense. I did not consider nested namespaces.

>Also, the logic does not check if the exception contains the current namespace, but whether the current namespace contains the exception, so your example will match as expected.

Ah yes, I had gotten haystack and needle mixed up.

So without doing any actual testing myself (since I think I can mange ACLs without adding an extra layer of protection) I'll close this issue. Sorry for the noise ;-)
